// Code generated by MockGen. DO NOT EDIT.
// Source: ./pkg/handler/dashboard/util/interface.go

// Package mock_util is a generated GoMock package.
package mock_util

import (
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockIUtil is a mock of IUtil interface.
type MockIUtil struct {
	ctrl     *gomock.Controller
	recorder *MockIUtilMockRecorder
}

// MockIUtilMockRecorder is the mock recorder for MockIUtil.
type MockIUtilMockRecorder struct {
	mock *MockIUtil
}

// NewMockIUtil creates a new mock instance.
func NewMockIUtil(ctrl *gomock.Controller) *MockIUtil {
	mock := &MockIUtil{ctrl: ctrl}
	mock.recorder = &MockIUtilMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIUtil) EXPECT() *MockIUtilMockRecorder {
	return m.recorder
}

// TimeNow mocks base method.
func (m *MockIUtil) TimeNow() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TimeNow")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// TimeNow indicates an expected call of TimeNow.
func (mr *MockIUtilMockRecorder) TimeNow() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TimeNow", reflect.TypeOf((*MockIUtil)(nil).TimeNow))
}
