// Code generated by MockGen. DO NOT EDIT.
// Source: ./pkg/service/notion/interface.go

// Package mock_notion is a generated GoMock package.
package mock_notion

import (
	reflect "reflect"
	time "time"

	notion "github.com/dstotijn/go-notion"
	model "github.com/dwarvesf/fortress-api/pkg/model"
	notion0 "github.com/dwarvesf/fortress-api/pkg/service/notion"
	gomock "github.com/golang/mock/gomock"
)

// MockIService is a mock of IService interface.
type MockIService struct {
	ctrl     *gomock.Controller
	recorder *MockIServiceMockRecorder
}

// MockIServiceMockRecorder is the mock recorder for MockIService.
type MockIServiceMockRecorder struct {
	mock *MockIService
}

// NewMockIService creates a new mock instance.
func NewMockIService(ctrl *gomock.Controller) *MockIService {
	mock := &MockIService{ctrl: ctrl}
	mock.recorder = &MockIServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIService) EXPECT() *MockIServiceMockRecorder {
	return m.recorder
}

// CheckInvoiceExistsForMonth mocks base method.
func (m *MockIService) CheckInvoiceExistsForMonth(projectPageID string, year, month int) (bool, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckInvoiceExistsForMonth", projectPageID, year, month)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CheckInvoiceExistsForMonth indicates an expected call of CheckInvoiceExistsForMonth.
func (mr *MockIServiceMockRecorder) CheckInvoiceExistsForMonth(projectPageID, year, month interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckInvoiceExistsForMonth", reflect.TypeOf((*MockIService)(nil).CheckInvoiceExistsForMonth), projectPageID, year, month)
}

// CloneInvoiceToNextMonth mocks base method.
func (m *MockIService) CloneInvoiceToNextMonth(sourceInvoicePageID string, targetIssueDate time.Time) (*notion0.ClonedInvoiceResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloneInvoiceToNextMonth", sourceInvoicePageID, targetIssueDate)
	ret0, _ := ret[0].(*notion0.ClonedInvoiceResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CloneInvoiceToNextMonth indicates an expected call of CloneInvoiceToNextMonth.
func (mr *MockIServiceMockRecorder) CloneInvoiceToNextMonth(sourceInvoicePageID, targetIssueDate interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloneInvoiceToNextMonth", reflect.TypeOf((*MockIService)(nil).CloneInvoiceToNextMonth), sourceInvoicePageID, targetIssueDate)
}

// CreateDatabaseRecord mocks base method.
func (m *MockIService) CreateDatabaseRecord(databaseID string, properties map[string]interface{}) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDatabaseRecord", databaseID, properties)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDatabaseRecord indicates an expected call of CreateDatabaseRecord.
func (mr *MockIServiceMockRecorder) CreateDatabaseRecord(databaseID, properties interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDatabaseRecord", reflect.TypeOf((*MockIService)(nil).CreateDatabaseRecord), databaseID, properties)
}

// CreatePage mocks base method.
func (m *MockIService) CreatePage() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePage")
	ret0, _ := ret[0].(error)
	return ret0
}

// CreatePage indicates an expected call of CreatePage.
func (mr *MockIServiceMockRecorder) CreatePage() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePage", reflect.TypeOf((*MockIService)(nil).CreatePage))
}

// ExtractClientInvoiceData mocks base method.
func (m *MockIService) ExtractClientInvoiceData(page *notion.Page) (*model.Invoice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExtractClientInvoiceData", page)
	ret0, _ := ret[0].(*model.Invoice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExtractClientInvoiceData indicates an expected call of ExtractClientInvoiceData.
func (mr *MockIServiceMockRecorder) ExtractClientInvoiceData(page interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExtractClientInvoiceData", reflect.TypeOf((*MockIService)(nil).ExtractClientInvoiceData), page)
}

// FindClientPageForChangelog mocks base method.
func (m *MockIService) FindClientPageForChangelog(clientID string) (notion.Page, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindClientPageForChangelog", clientID)
	ret0, _ := ret[0].(notion.Page)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindClientPageForChangelog indicates an expected call of FindClientPageForChangelog.
func (mr *MockIServiceMockRecorder) FindClientPageForChangelog(clientID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindClientPageForChangelog", reflect.TypeOf((*MockIService)(nil).FindClientPageForChangelog), clientID)
}

// GetBlock mocks base method.
func (m *MockIService) GetBlock(pageID string) (notion.Block, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlock", pageID)
	ret0, _ := ret[0].(notion.Block)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlock indicates an expected call of GetBlock.
func (mr *MockIServiceMockRecorder) GetBlock(pageID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlock", reflect.TypeOf((*MockIService)(nil).GetBlock), pageID)
}

// GetBlockChildren mocks base method.
func (m *MockIService) GetBlockChildren(pageID string) (*notion.BlockChildrenResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlockChildren", pageID)
	ret0, _ := ret[0].(*notion.BlockChildrenResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlockChildren indicates an expected call of GetBlockChildren.
func (mr *MockIServiceMockRecorder) GetBlockChildren(pageID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlockChildren", reflect.TypeOf((*MockIService)(nil).GetBlockChildren), pageID)
}

// GetDatabase mocks base method.
func (m *MockIService) GetDatabase(databaseID string, filter *notion.DatabaseQueryFilter, sorts []notion.DatabaseQuerySort, pageSize int) (*notion.DatabaseQueryResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDatabase", databaseID, filter, sorts, pageSize)
	ret0, _ := ret[0].(*notion.DatabaseQueryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDatabase indicates an expected call of GetDatabase.
func (mr *MockIServiceMockRecorder) GetDatabase(databaseID, filter, sorts, pageSize interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDatabase", reflect.TypeOf((*MockIService)(nil).GetDatabase), databaseID, filter, sorts, pageSize)
}

// GetDatabaseWithStartCursor mocks base method.
func (m *MockIService) GetDatabaseWithStartCursor(databaseID, startCursor string) (*notion.DatabaseQueryResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDatabaseWithStartCursor", databaseID, startCursor)
	ret0, _ := ret[0].(*notion.DatabaseQueryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDatabaseWithStartCursor indicates an expected call of GetDatabaseWithStartCursor.
func (mr *MockIServiceMockRecorder) GetDatabaseWithStartCursor(databaseID, startCursor interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDatabaseWithStartCursor", reflect.TypeOf((*MockIService)(nil).GetDatabaseWithStartCursor), databaseID, startCursor)
}

// GetInvoiceLineItems mocks base method.
func (m *MockIService) GetInvoiceLineItems(invoicePageID string) ([]notion.Page, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInvoiceLineItems", invoicePageID)
	ret0, _ := ret[0].([]notion.Page)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInvoiceLineItems indicates an expected call of GetInvoiceLineItems.
func (mr *MockIServiceMockRecorder) GetInvoiceLineItems(invoicePageID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInvoiceLineItems", reflect.TypeOf((*MockIService)(nil).GetInvoiceLineItems), invoicePageID)
}

// GetNotionInvoiceStatus mocks base method.
func (m *MockIService) GetNotionInvoiceStatus(page *notion.Page) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNotionInvoiceStatus", page)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNotionInvoiceStatus indicates an expected call of GetNotionInvoiceStatus.
func (mr *MockIServiceMockRecorder) GetNotionInvoiceStatus(page interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNotionInvoiceStatus", reflect.TypeOf((*MockIService)(nil).GetNotionInvoiceStatus), page)
}

// GetPage mocks base method.
func (m *MockIService) GetPage(pageID string) (notion.Page, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPage", pageID)
	ret0, _ := ret[0].(notion.Page)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPage indicates an expected call of GetPage.
func (mr *MockIServiceMockRecorder) GetPage(pageID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPage", reflect.TypeOf((*MockIService)(nil).GetPage), pageID)
}

// GetPagePropByID mocks base method.
func (m *MockIService) GetPagePropByID(pageID, propID string, query *notion.PaginationQuery) (*notion.PagePropResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPagePropByID", pageID, propID, query)
	ret0, _ := ret[0].(*notion.PagePropResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPagePropByID indicates an expected call of GetPagePropByID.
func (mr *MockIServiceMockRecorder) GetPagePropByID(pageID, propID, query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPagePropByID", reflect.TypeOf((*MockIService)(nil).GetPagePropByID), pageID, propID, query)
}

// GetProjectHeadEmails mocks base method.
func (m *MockIService) GetProjectHeadEmails(pageID string) (string, string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProjectHeadEmails", pageID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(string)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// GetProjectHeadEmails indicates an expected call of GetProjectHeadEmails.
func (mr *MockIServiceMockRecorder) GetProjectHeadEmails(pageID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProjectHeadEmails", reflect.TypeOf((*MockIService)(nil).GetProjectHeadEmails), pageID)
}

// GetProjectInDB mocks base method.
func (m *MockIService) GetProjectInDB(pageID string) (*notion.DatabasePageProperties, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProjectInDB", pageID)
	ret0, _ := ret[0].(*notion.DatabasePageProperties)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProjectInDB indicates an expected call of GetProjectInDB.
func (mr *MockIServiceMockRecorder) GetProjectInDB(pageID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProjectInDB", reflect.TypeOf((*MockIService)(nil).GetProjectInDB), pageID)
}

// GetProjectsInDB mocks base method.
func (m *MockIService) GetProjectsInDB(pageIDs []string, projectPageID string) (map[string]notion.DatabasePageProperties, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProjectsInDB", pageIDs, projectPageID)
	ret0, _ := ret[0].(map[string]notion.DatabasePageProperties)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProjectsInDB indicates an expected call of GetProjectsInDB.
func (mr *MockIServiceMockRecorder) GetProjectsInDB(pageIDs, projectPageID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProjectsInDB", reflect.TypeOf((*MockIService)(nil).GetProjectsInDB), pageIDs, projectPageID)
}

// IsSplitsGenerated mocks base method.
func (m *MockIService) IsSplitsGenerated(invoicePageID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsSplitsGenerated", invoicePageID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsSplitsGenerated indicates an expected call of IsSplitsGenerated.
func (mr *MockIServiceMockRecorder) IsSplitsGenerated(invoicePageID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsSplitsGenerated", reflect.TypeOf((*MockIService)(nil).IsSplitsGenerated), invoicePageID)
}

// ListProjects mocks base method.
func (m *MockIService) ListProjects() ([]model.NotionProject, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProjects")
	ret0, _ := ret[0].([]model.NotionProject)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProjects indicates an expected call of ListProjects.
func (mr *MockIServiceMockRecorder) ListProjects() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProjects", reflect.TypeOf((*MockIService)(nil).ListProjects))
}

// ListProjectsWithChangelog mocks base method.
func (m *MockIService) ListProjectsWithChangelog() ([]model.ProjectChangelogPage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProjectsWithChangelog")
	ret0, _ := ret[0].([]model.ProjectChangelogPage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProjectsWithChangelog indicates an expected call of ListProjectsWithChangelog.
func (mr *MockIServiceMockRecorder) ListProjectsWithChangelog() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProjectsWithChangelog", reflect.TypeOf((*MockIService)(nil).ListProjectsWithChangelog))
}

// MarkLineItemsSplitsGenerated mocks base method.
func (m *MockIService) MarkLineItemsSplitsGenerated(invoicePageID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkLineItemsSplitsGenerated", invoicePageID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkLineItemsSplitsGenerated indicates an expected call of MarkLineItemsSplitsGenerated.
func (mr *MockIServiceMockRecorder) MarkLineItemsSplitsGenerated(invoicePageID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkLineItemsSplitsGenerated", reflect.TypeOf((*MockIService)(nil).MarkLineItemsSplitsGenerated), invoicePageID)
}

// MarkSplitsGenerated mocks base method.
func (m *MockIService) MarkSplitsGenerated(invoicePageID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkSplitsGenerated", invoicePageID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkSplitsGenerated indicates an expected call of MarkSplitsGenerated.
func (mr *MockIServiceMockRecorder) MarkSplitsGenerated(invoicePageID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkSplitsGenerated", reflect.TypeOf((*MockIService)(nil).MarkSplitsGenerated), invoicePageID)
}

// QueryAudienceDatabase mocks base method.
func (m *MockIService) QueryAudienceDatabase(audienceDBId, audience string) ([]notion.Page, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryAudienceDatabase", audienceDBId, audience)
	ret0, _ := ret[0].([]notion.Page)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryAudienceDatabase indicates an expected call of QueryAudienceDatabase.
func (mr *MockIServiceMockRecorder) QueryAudienceDatabase(audienceDBId, audience interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryAudienceDatabase", reflect.TypeOf((*MockIService)(nil).QueryAudienceDatabase), audienceDBId, audience)
}

// QueryClientInvoiceByNumber mocks base method.
func (m *MockIService) QueryClientInvoiceByNumber(invoiceNumber string) (*notion.Page, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryClientInvoiceByNumber", invoiceNumber)
	ret0, _ := ret[0].(*notion.Page)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryClientInvoiceByNumber indicates an expected call of QueryClientInvoiceByNumber.
func (mr *MockIServiceMockRecorder) QueryClientInvoiceByNumber(invoiceNumber interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryClientInvoiceByNumber", reflect.TypeOf((*MockIService)(nil).QueryClientInvoiceByNumber), invoiceNumber)
}

// QueryInvoices mocks base method.
func (m *MockIService) QueryInvoices(filter *notion0.InvoiceFilter, pagination model.Pagination) ([]notion.Page, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryInvoices", filter, pagination)
	ret0, _ := ret[0].([]notion.Page)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// QueryInvoices indicates an expected call of QueryInvoices.
func (mr *MockIServiceMockRecorder) QueryInvoices(filter, pagination interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryInvoices", reflect.TypeOf((*MockIService)(nil).QueryInvoices), filter, pagination)
}

// QueryInvoicesByMonth mocks base method.
func (m *MockIService) QueryInvoicesByMonth(year, month int, statuses []string, projectID string) ([]notion.Page, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryInvoicesByMonth", year, month, statuses, projectID)
	ret0, _ := ret[0].([]notion.Page)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryInvoicesByMonth indicates an expected call of QueryInvoicesByMonth.
func (mr *MockIServiceMockRecorder) QueryInvoicesByMonth(year, month, statuses, projectID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryInvoicesByMonth", reflect.TypeOf((*MockIService)(nil).QueryInvoicesByMonth), year, month, statuses, projectID)
}

// QueryLineItemsWithCommissions mocks base method.
func (m *MockIService) QueryLineItemsWithCommissions(invoicePageID string) ([]notion0.LineItemCommissionData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryLineItemsWithCommissions", invoicePageID)
	ret0, _ := ret[0].([]notion0.LineItemCommissionData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryLineItemsWithCommissions indicates an expected call of QueryLineItemsWithCommissions.
func (mr *MockIServiceMockRecorder) QueryLineItemsWithCommissions(invoicePageID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryLineItemsWithCommissions", reflect.TypeOf((*MockIService)(nil).QueryLineItemsWithCommissions), invoicePageID)
}

// ToChangelogMJML mocks base method.
func (m *MockIService) ToChangelogMJML(blocks []notion.Block, email model.Email) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToChangelogMJML", blocks, email)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ToChangelogMJML indicates an expected call of ToChangelogMJML.
func (mr *MockIServiceMockRecorder) ToChangelogMJML(blocks, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToChangelogMJML", reflect.TypeOf((*MockIService)(nil).ToChangelogMJML), blocks, email)
}

// UpdateClientInvoiceStatus mocks base method.
func (m *MockIService) UpdateClientInvoiceStatus(pageID, status string, paidDate *time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateClientInvoiceStatus", pageID, status, paidDate)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateClientInvoiceStatus indicates an expected call of UpdateClientInvoiceStatus.
func (mr *MockIServiceMockRecorder) UpdateClientInvoiceStatus(pageID, status, paidDate interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateClientInvoiceStatus", reflect.TypeOf((*MockIService)(nil).UpdateClientInvoiceStatus), pageID, status, paidDate)
}

// UpdateLineItemsStatus mocks base method.
func (m *MockIService) UpdateLineItemsStatus(invoicePageID, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLineItemsStatus", invoicePageID, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLineItemsStatus indicates an expected call of UpdateLineItemsStatus.
func (mr *MockIServiceMockRecorder) UpdateLineItemsStatus(invoicePageID, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLineItemsStatus", reflect.TypeOf((*MockIService)(nil).UpdateLineItemsStatus), invoicePageID, status)
}

// UpdatePageProperties mocks base method.
func (m *MockIService) UpdatePageProperties(pageID string, properties notion.UpdatePageParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePageProperties", pageID, properties)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePageProperties indicates an expected call of UpdatePageProperties.
func (mr *MockIServiceMockRecorder) UpdatePageProperties(pageID, properties interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePageProperties", reflect.TypeOf((*MockIService)(nil).UpdatePageProperties), pageID, properties)
}

// UpdatePagePropertiesWithFileUpload mocks base method.
func (m *MockIService) UpdatePagePropertiesWithFileUpload(pageID, propertyName, fileUploadID, filename string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePagePropertiesWithFileUpload", pageID, propertyName, fileUploadID, filename)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePagePropertiesWithFileUpload indicates an expected call of UpdatePagePropertiesWithFileUpload.
func (mr *MockIServiceMockRecorder) UpdatePagePropertiesWithFileUpload(pageID, propertyName, fileUploadID, filename interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePagePropertiesWithFileUpload", reflect.TypeOf((*MockIService)(nil).UpdatePagePropertiesWithFileUpload), pageID, propertyName, fileUploadID, filename)
}

// UploadFile mocks base method.
func (m *MockIService) UploadFile(filename, contentType string, fileData []byte) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadFile", filename, contentType, fileData)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadFile indicates an expected call of UploadFile.
func (mr *MockIServiceMockRecorder) UploadFile(filename, contentType, fileData interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadFile", reflect.TypeOf((*MockIService)(nil).UploadFile), filename, contentType, fileData)
}
