version: "2"

# https://golangci-lint.run/usage/linters/
linters:
  default: none
  enable:
  # default (gosimple merged into staticcheck in v2)
    - errcheck # Errcheck is a program for checking for unchecked errors in go programs. These unchecked errors can be critical bugs in some cases
    - govet # Vet examines Go source code and reports suspicious constructs, such as Printf calls whose arguments do not align with the format string
    - ineffassign # Detects when assignments to existing variables are not used
    - staticcheck # It's the set of rules from staticcheck (includes gosimple in v2)
    - unused # Checks Go code for unused constants, variables, functions and types

  # customize
    # - execinquery # execinquery is deprecated since v1.58.0
    # - errorlint # errorlint is a linter for that can be used to find code that will cause problems with the error wrapping scheme introduced in Go 1.13.
    - bodyclose # checks whether HTTP response body is closed successfully
    - errname # Checks that sentinel errors are prefixed with the Err and error types are suffixed with the Error.
    - unconvert # Remove unnecessary type conversions
    - whitespace # Tool for detection of leading and trailing whitespace

    # - gofumpt # Gofumpt checks whether code was gofumpt-ed.
    # - lll # Reports long lines
    - misspell # Finds commonly misspelled English words in comments
    # - usestdlibvars # A linter that detect the possibility to use variables/constants from the Go standard library.
    # - revive

  settings:
    misspell:
      locale: US
      ignore:
        - cancelled
        - Cancelled
    lll:
      line-length: 140

  exclusions:
    rules:
      # Exclude some `staticcheck` messages.
      - linters:
          - staticcheck
        text: "SA1019:"
      
      # Exclude pre-existing errcheck issues for unchecked Close() calls in existing code
      # This broad exclusion ignores Close() errors but allows other errcheck rules
      - linters:
          - errcheck
        text: "Error return value of .*(Close|close).*is not checked"
      
      # Exclude errcheck for GORM callback registration in monitoring (intentional)
      - path: "pkg/store/monitoring.go"
        linters:
          - errcheck
        text: "Error return value of.*Register.*is not checked"
      
      # Exclude pre-existing staticcheck issues in existing code
      - linters:
          - staticcheck
        text: "(QF1004|QF1007|QF1008|QF1011|ST1005|ST1023|QF1001):"
      
      # Allow monitoring code to use for-select pattern (legitimate use case)
      - path: "pkg/security/threat_detector.go"
        linters:
          - staticcheck
        text: "S1000: should use for range instead of for"
      - path: "pkg/store/monitoring.go"
        linters:
          - staticcheck
        text: "S1000: should use for range instead of for"

run:
  timeout: 5m