basePath: /api/v1
definitions:
  model.AccountStatus:
    properties:
      code:
        type: string
      createdAt:
        type: string
      deletedAt:
        type: string
      id:
        type: string
      name:
        type: string
      updatedAt:
        type: string
    type: object
  model.Country:
    properties:
      cities:
        items:
          type: string
        type: array
      code:
        type: string
      createdAt:
        type: string
      deletedAt:
        type: string
      id:
        type: string
      name:
        type: string
      updatedAt:
        type: string
    type: object
  model.Position:
    properties:
      code:
        type: string
      createdAt:
        type: string
      deletedAt:
        type: string
      id:
        type: string
      name:
        type: string
      updatedAt:
        type: string
    type: object
  model.Role:
    properties:
      code:
        type: string
      createdAt:
        type: string
      deletedAt:
        type: string
      id:
        type: string
      name:
        type: string
      updatedAt:
        type: string
    type: object
  view.AccountRoleResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/model.Role'
        type: array
    type: object
  view.AccountStatusResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/model.AccountStatus'
        type: array
    type: object
  view.ApiError:
    description: validation error details
    properties:
      enums:
        description: available options incase of field's payload is enums
        items:
          type: string
        type: array
      field:
        description: the field cause the error
        type: string
      msg:
        description: error message
        type: string
    type: object
  view.AuthData:
    properties:
      accessToken:
        type: string
      employee:
        $ref: '#/definitions/view.EmployeeListData'
    type: object
  view.CitiesResponse:
    properties:
      data:
        items:
          type: string
        type: array
    type: object
  view.CountriesResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/model.Country'
        type: array
    type: object
  view.EmployeeListData:
    properties:
      address:
        type: string
      avatar:
        type: string
      birthday:
        type: string
      createdAt:
        type: string
      deletedAt:
        type: string
      displayName:
        type: string
      fullName:
        description: basic info
        type: string
      gender:
        type: string
      horoscope:
        type: string
      id:
        type: string
      joinedDate:
        type: string
      leftDate:
        type: string
      mbti:
        type: string
      personalEmail:
        type: string
      phoneNumber:
        type: string
      status:
        description: working info
        type: string
      teamEmail:
        type: string
      updatedAt:
        type: string
    type: object
  view.ErrorResponse:
    properties:
      error:
        type: string
      errors:
        items:
          $ref: '#/definitions/view.ApiError'
        type: array
    type: object
  view.PositionResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/model.Position'
        type: array
    type: object
  view.WorkingStatusData:
    properties:
      id:
        type: string
      name:
        type: string
    type: object
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /auth:
    post:
      consumes:
      - application/json
      description: Authorise user when login
      parameters:
      - description: Google login code
        in: body
        name: code
        required: true
        schema:
          type: string
      - description: Google redirect url
        in: body
        name: redirectUrl
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/view.AuthData'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/view.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/view.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/view.ErrorResponse'
      summary: Authorise user when login
      tags:
      - Auth
  /employee/{id}:
    get:
      consumes:
      - application/json
      description: Get employee by id
      parameters:
      - description: Employee ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/view.EmployeeListData'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/view.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/view.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/view.ErrorResponse'
      summary: Get employee by id
      tags:
      - Employee
  /metadata/account-roles:
    get:
      consumes:
      - application/json
      description: Get list values for account roles
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/view.AccountRoleResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/view.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/view.ErrorResponse'
      summary: Get list values for account roles
      tags:
      - Metadata
  /metadata/account-statuses:
    get:
      consumes:
      - application/json
      description: Get list values for account statuses
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/view.AccountStatusResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/view.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/view.ErrorResponse'
      summary: Get list values for account statuses
      tags:
      - Metadata
  /metadata/countries:
    get:
      consumes:
      - application/json
      description: Get all countries
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/view.CountriesResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/view.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/view.ErrorResponse'
      summary: Get all countries
      tags:
      - Metadata
  /metadata/countries/:country_id/cities:
    get:
      consumes:
      - application/json
      description: Get list cities by country
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/view.CitiesResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/view.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/view.ErrorResponse'
      summary: Get list cities by country
      tags:
      - Metadata
  /metadata/positions:
    get:
      consumes:
      - application/json
      description: Get list values for positions
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/view.PositionResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/view.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/view.ErrorResponse'
      summary: Get list values for positions
      tags:
      - Metadata
  /metadata/working-status:
    get:
      consumes:
      - application/json
      description: Get list values for working status
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/view.WorkingStatusData'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/view.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/view.ErrorResponse'
      summary: Get list values for working status
      tags:
      - Metadata
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
