basePath: /api/v1
definitions:
  model.Chapter:
    properties:
      code:
        type: string
      createdAt:
        type: string
      deletedAt:
        type: string
      id:
        type: string
      name:
        type: string
      updatedAt:
        type: string
    type: object
  model.Country:
    properties:
      cities:
        items:
          type: string
        type: array
      code:
        type: string
      createdAt:
        type: string
      deletedAt:
        type: string
      id:
        type: string
      name:
        type: string
      updatedAt:
        type: string
    type: object
  model.Position:
    properties:
      code:
        type: string
      createdAt:
        type: string
      deletedAt:
        type: string
      id:
        type: string
      name:
        type: string
      updatedAt:
        type: string
    type: object
  model.Role:
    properties:
      code:
        type: string
      createdAt:
        type: string
      deletedAt:
        type: string
      id:
        type: string
      name:
        type: string
      updatedAt:
        type: string
    type: object
  model.Seniority:
    properties:
      code:
        type: string
      createdAt:
        type: string
      deletedAt:
        type: string
      id:
        type: string
      name:
        type: string
      updatedAt:
        type: string
    type: object
  view.AccountRoleResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/model.Role'
        type: array
    type: object
  view.ApiError:
    description: validation error details
    properties:
      enums:
        description: available options incase of field's payload is enums
        items:
          type: string
        type: array
      field:
        description: the field cause the error
        type: string
      msg:
        description: error message
        type: string
    type: object
  view.AuthData:
    properties:
      accessToken:
        type: string
      employee:
        $ref: '#/definitions/view.EmployeeData'
    type: object
  view.ChapterResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/model.Chapter'
        type: array
    type: object
  view.CitiesResponse:
    properties:
      data:
        items:
          type: string
        type: array
    type: object
  view.CountriesResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/model.Country'
        type: array
    type: object
  view.EmployeeData:
    properties:
      address:
        type: string
      avatar:
        type: string
      birthday:
        type: string
      createdAt:
        type: string
      deletedAt:
        type: string
      displayName:
        type: string
      fullName:
        description: basic info
        type: string
      gender:
        type: string
      horoscope:
        type: string
      id:
        type: string
      joinedDate:
        type: string
      leftDate:
        type: string
      mbti:
        type: string
      personalEmail:
        type: string
      phoneNumber:
        type: string
      status:
        description: working info
        type: string
      teamEmail:
        type: string
      updatedAt:
        type: string
    type: object
  view.EmployeeListDataResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/view.EmployeeData'
        type: array
    type: object
  view.ErrorResponse:
    properties:
      error:
        type: string
      errors:
        items:
          $ref: '#/definitions/view.ApiError'
        type: array
    type: object
  view.MetaData:
    properties:
      code:
        type: string
      name:
        type: string
    type: object
  view.PositionResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/model.Position'
        type: array
    type: object
  view.ProfileData:
    properties:
      avatar:
        type: string
      birthday:
        type: string
      discordId:
        type: string
      displayName:
        type: string
      fullName:
        type: string
      gender:
        type: string
      githubId:
        type: string
      id:
        type: string
      personalEmail:
        type: string
      phoneNumber:
        type: string
      teamEmail:
        type: string
    type: object
  view.ProfileDataResponse:
    properties:
      data:
        $ref: '#/definitions/view.ProfileData'
    type: object
  view.ProjectData:
    properties:
      createdAt:
        type: string
      deletedAt:
        type: string
      endDate:
        type: string
      heads:
        items:
          $ref: '#/definitions/view.ProjectHead'
        type: array
      id:
        type: string
      members:
        items:
          $ref: '#/definitions/view.ProjectMember'
        type: array
      name:
        type: string
      startDate:
        type: string
      status:
        type: string
      type:
        type: string
      updatedAt:
        type: string
    type: object
  view.ProjectHead:
    properties:
      avatar:
        type: string
      displayName:
        type: string
      employeeID:
        type: string
      fullName:
        type: string
      position:
        type: string
    type: object
  view.ProjectListDataResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/view.ProjectData'
        type: array
    type: object
  view.ProjectMember:
    properties:
      avatar:
        type: string
      displayName:
        type: string
      employeeID:
        type: string
      fullName:
        type: string
      isLead:
        type: boolean
    type: object
  view.SeniorityResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/model.Seniority'
        type: array
    type: object
  view.UpdataEmployeeStatusResponse:
    properties:
      data:
        $ref: '#/definitions/view.EmployeeData'
    type: object
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /auth:
    post:
      consumes:
      - application/json
      description: Authorise user when login
      parameters:
      - description: Google login code
        in: body
        name: code
        required: true
        schema:
          type: string
      - description: Google redirect url
        in: body
        name: redirectUrl
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/view.AuthData'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/view.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/view.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/view.ErrorResponse'
      summary: Authorise user when login
      tags:
      - Auth
  /employees:
    get:
      consumes:
      - application/json
      description: Get the list of employees with pagination and workingStatus
      parameters:
      - description: jwt token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Working Status
        in: query
        name: workingStatus
        required: true
        type: string
      - description: Page
        in: query
        name: page
        required: true
        type: string
      - description: Size
        in: query
        name: size
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/view.EmployeeListDataResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/view.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/view.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/view.ErrorResponse'
      summary: Get the list of employees
      tags:
      - Employee
  /employees/{id}:
    get:
      consumes:
      - application/json
      description: Get employee by id
      parameters:
      - description: Employee ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/view.EmployeeData'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/view.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/view.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/view.ErrorResponse'
      summary: Get employee by id
      tags:
      - Employee
  /employees/{id}/employee-status:
    post:
      consumes:
      - application/json
      description: Update account status by employee id
      parameters:
      - description: Employee ID
        in: path
        name: id
        required: true
        type: string
      - description: Employee Status
        in: body
        name: employeeStatus
        required: true
        schema:
          type: string
      - description: jwt token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/view.UpdataEmployeeStatusResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/view.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/view.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/view.ErrorResponse'
      summary: Update account status by employee id
      tags:
      - Employee
  /metadata/account-roles:
    get:
      consumes:
      - application/json
      description: Get list values for account roles
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/view.AccountRoleResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/view.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/view.ErrorResponse'
      summary: Get list values for account roles
      tags:
      - Metadata
  /metadata/account-statuses:
    get:
      consumes:
      - application/json
      description: Get list values for account statuses
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/view.MetaData'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/view.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/view.ErrorResponse'
      summary: Get list values for account statuses
      tags:
      - Metadata
  /metadata/chapters:
    get:
      consumes:
      - application/json
      description: Get list values for chapters
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/view.ChapterResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/view.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/view.ErrorResponse'
      summary: Get list values for chapters
      tags:
      - Metadata
  /metadata/countries:
    get:
      consumes:
      - application/json
      description: Get all countries
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/view.CountriesResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/view.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/view.ErrorResponse'
      summary: Get all countries
      tags:
      - Metadata
  /metadata/countries/:country_id/cities:
    get:
      consumes:
      - application/json
      description: Get list cities by country
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/view.CitiesResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/view.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/view.ErrorResponse'
      summary: Get list cities by country
      tags:
      - Metadata
  /metadata/positions:
    get:
      consumes:
      - application/json
      description: Get list values for positions
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/view.PositionResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/view.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/view.ErrorResponse'
      summary: Get list values for positions
      tags:
      - Metadata
  /metadata/project-statuses:
    get:
      consumes:
      - application/json
      description: Get list values for project statuses
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/view.MetaData'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/view.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/view.ErrorResponse'
      summary: Get list values for project statuses
      tags:
      - Metadata
  /metadata/seniorities:
    get:
      consumes:
      - application/json
      description: Get list values for sentitorities
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/view.SeniorityResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/view.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/view.ErrorResponse'
      summary: Get list values for sentitorities
      tags:
      - Metadata
  /metadata/working-status:
    get:
      consumes:
      - application/json
      description: Get list values for working status
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/view.MetaData'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/view.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/view.ErrorResponse'
      summary: Get list values for working status
      tags:
      - Metadata
  /profile:
    get:
      consumes:
      - application/json
      description: Get profile information of employee
      parameters:
      - description: jwt token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/view.ProfileDataResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/view.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/view.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/view.ErrorResponse'
      summary: Get profile information of employee
      tags:
      - Employee
  /projects:
    get:
      consumes:
      - application/json
      description: Get list of project
      parameters:
      - description: jwt token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Project status
        in: query
        name: status
        type: string
      - description: Project name
        in: query
        name: name
        type: string
      - description: Project type
        in: query
        name: type
        type: string
      - description: Page
        in: query
        name: page
        type: string
      - description: Size
        in: query
        name: size
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/view.ProjectListDataResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/view.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/view.ErrorResponse'
      summary: Get list of project
      tags:
      - Project
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
