name: Build tools image

on:
  push:
    branches:
      - develop
    paths:
      - tools.Dockerfile
      - go.mod

# Environment variables available to all jobs and steps in this workflow
env:
  GITHUB_SHA: ${{ github.sha }}
  PROJECT: dwarvesv
  IMAGE: fortress-tools

jobs:
  setup-build-publish:
    name: Build tools image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build & Push the Docker image
      - name: Build & Push
        run: |
          docker build -f tools.Dockerfile -t $PROJECT/${IMAGE}:${GITHUB_SHA} .
          docker push $PROJECT/${IMAGE}:${GITHUB_SHA}

          docker tag $PROJECT/${IMAGE}:${GITHUB_SHA} $PROJECT/${IMAGE}:latest
          docker push $PROJECT/${IMAGE}:latest
