name: golangci-lint

on:
  pull_request:
permissions:
  contents: read
  # Allow read access to pull request for only-new-issues option
  pull-requests: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24.1'
      - uses: actions/checkout@v4
      - name: build
        run: go mod download
      - name: verify golangci-lint config
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v2.1.6
          $(go env GOPATH)/bin/golangci-lint config verify
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          # Use stable version that supports Go 1.24+
          version: v2.1

          # Optional: working directory, useful for monorepos
          # working-directory: somedir

          # Optional: golangci-lint command line arguments.
          # args: --issues-exit-code=0

          # Show only new issues if it's a pull request
          only-new-issues: true

          # Optional: if set to true then the all caching functionality will be complete disabled,
          #           takes precedence over all other caching options.
          # skip-cache: true

          # Optional: if set to true then the action don't cache or restore ~/go/pkg.
          skip-pkg-cache: true

          # Optional: if set to true then the action don't cache or restore ~/.cache/go-build.
          # skip-build-cache: true
